### ISSUE TITLE
Remove proprietary references

### ISSUE THREAD

**Issue by avaer** [adrianhopebailie/web-monetization#4] opened 2019-08-14 18:00 UTC
I see the explainer is referencing Coil/Interledger to explain the concepts, but that’s kind of doing it a dis-service as an aspirational open standard.

Is it possible to remove these references and point to public domain runnable implementations we could discuss instead, without reference to any specific entities driving the spec?

**Comment by adrianhopebailie** [comment] 2019-08-15 14:44
Can you clarify why you think Interledger is proprietary?

With regard to this request:
> point to public domain runnable implementations

It would be useful if you could explain the ask a bit more clearly. Coil is a **WM Provider** as defined in the explainer.

A **WM Provider** is an entity, not a piece of code so it's hard to understand what you're asking for.

If I were to guess, I'd assume you mean something like: "If WM is an open standard what options do I have for choosing a WM Provider?"

Or more importantly: "Can I be my own WM Provider?"

There is a long answer to that which I'm happy to add to the explainer if that indeed is the question.

**Comment by justmoon** [comment] 2019-08-15 21:52
@adrianhopebailie I think the issue is just that the document references "Coil" which is the name of one specific company implementing the standard which is an unusual thing to mention in a standards document.

If you just delete all of the references to Coil and just say WM Provider instead that would address the concern for me.

Interledger is an open standard developed by members of the W3C Interledger Community Group so referencing Interledger should be fine.

**Comment by adrianhopebailie** [comment] 2019-08-18 20:00
Done. Unfortunately I fully expect the next question to be something along the lines of:

> The explainer says: "This proposal is modelled on a working implementation that uses a browser extension to provide the necessary browser-side functionality", where can I see this implementation?

**Comment by justmoon** [comment] 2019-08-20 16:51
Rather than mentioning Coil in the text, maybe there should be a "list of implementations" section somewhere at the end? I don't know what the usual etiquette is around this.

**Comment by marcoscaceres** [comment] 2019-08-21 05:00
@justmoon, yes, it's not unusual to include a list of implementations at the end... specially for an explainer.

**Comment by adrianhopebailie** [comment] 2019-08-21 06:53
Fixed by #7 

@modulesio - this is your issue, are you okay for me to close it now?

**Comment by avaer** [comment] 2019-08-21 07:01
Yes, #7 LGTM.

I think it's appropriate to have an ongoing list of implementations at the end of the explainer.

**Closed as completed** 2019-08-21 07:12 UTC
